# Generated by Django 4.2.7 on 2023-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planet', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('lightsabercolor', models.CharField(max_length=100)),
                ('jeditype', models.CharField(choices=[('C', 'Consular'), ('S', 'Sentinel'), ('G', 'Guardian')], default='C', max_length=1)),
                ('mentor', models.CharField(choices=[('Y', 'Yoda'), ('K', 'Kit Fisto'), ('O', 'Obi-Wan Kenobi'), ('M', 'Mace Windu'), ('Q', 'Qui-Gon Jinn'), ('L', 'Luke Skywalker'), ('A', 'Anakin Skywalker'), ('C', 'Count Dooku')], default='Y', max_length=1)),
                ('powerlevel', models.IntegerField(default=0)),
                ('lightsaberskill', models.IntegerField(default=0)),
                ('forceabilities', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('stamina', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
            ],
        ),
    ]
