# Generated by Django 4.2.7 on 2023-11-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedi',
            name='planet',
            field=models.CharField(choices=[('T', 'Tatooine'), ('C', 'Coruscant'), ('N', 'Naboo'), ('K', 'Kamino'), ('D', 'Dagobah'), ('A', 'Alderaan'), ('M', 'Mustafar'), ('J', 'Jakku'), ('B', 'Bespin')], default='T', max_length=1),
        ),
    ]
