# Generated by Django 4.2.7 on 2023-11-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_jedi_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedi',
            name='lightsabercolor',
            field=models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('P', 'Purple'), ('Y', 'Yellow')], default='B', max_length=1),
        ),
    ]
