# Generated by Django 4.2.7 on 2023-11-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_jedi_lightsabercolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('L', 'Lightsaber Training'), ('M', 'Meditation'), ('S', 'Study of Jedi code'), ('T', 'Telekinesis'), ('F', 'Force Persuasion'), ('D', 'Diplomatic Training')], default='L', max_length=1)),
                ('jedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jedi')),
            ],
        ),
    ]
