# Generated by Django 4.2.7 on 2023-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Mission Date')),
                ('type', models.CharField(choices=[('R', 'Rescue Mission'), ('A', 'Artifact Retrieval'), ('P', 'Peacekeeping'), ('I', 'Infiltration'), ('E', 'Exploration'), ('S', 'Sabotage'), ('G', 'Guardian Mission'), ('C', 'Crisis Response'), ('B', 'Bounty Hunter Pursuit')], default='R', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Training Date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.CharField(choices=[('L', 'Lightsaber Training'), ('M', 'Meditation'), ('S', 'Study of Jedi code'), ('T', 'Telekinesis'), ('F', 'Force Persuasion'), ('D', 'Diplomatic Training')], default='L', max_length=1, verbose_name='Training Type'),
        ),
    ]
