# Generated by Django 4.2.7 on 2023-11-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_mission_alter_training_date_alter_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='jedi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.jedi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('R', 'Rescue Mission'), ('A', 'Artifact Retrieval'), ('P', 'Peacekeeping'), ('I', 'Infiltration'), ('E', 'Exploration'), ('S', 'Sabotage'), ('G', 'Guardian Mission'), ('C', 'Crisis Response'), ('B', 'Bounty Hunter Pursuit')], default='R', max_length=1, verbose_name='Mission Type'),
        ),
    ]
